name: sweetbook
description: Sweetbook main library
version: 0.2.3
homepage: https://github.com/iamguid/sweetbook

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  go_router: ^4.5.0
  agent_flutter: ^0.2.5
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
