name: sweetbook
version: 0.3.0
description: Sweetbook main library
homepage: https://github.com/iamguid/sweetbook
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  go_router: ^14.8.0
  agent_flutter: ^0.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
