name: sweetbook
description: Sweetbook main library
version: 0.2.7
homepage: https://github.com/iamguid/sweetbook

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  go_router: ^9.0.0
  agent_flutter: ^0.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
