name: sweetbook_workspace
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dev_dependencies:
  melos: ^7.0.0-dev.7

workspace:
  - packages/sweetbook
  - packages/sweetbook_cli
  - examples/sweetbook_basic

melos:
  scripts:
    upgrade:
      run: melos exec -- "flutter pub upgrade --major-versions"
      description: Upgrade all packages to the latest version.