name: sweetbook_cli
description: CLI tool for sweetbook library
version: 0.1.0
homepage: https://github.com/iamguid/sweetbook

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
