name: sweetbook_cli
version: 0.1.0
description: CLI tool for sweetbook library
homepage: https://github.com/iamguid/sweetbook
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
